name: Copy ASALI API
on:
  [ workflow_dispatch ]
jobs:

  build:
    name: Copy ASALI API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy asali.cpp
      uses: canastro/copy-file-action@master
      with:
        source: "API/Cpp/asali.cpp"
        target: "GUI/src/asali.cpp"
    - name: Copy asali.hpp
      uses: canastro/copy-file-action@master
      with:
        source: "API/Cpp/asali.hpp"
        target: "GUI/include/asali.cpp"
    - name: Copy thermo.H
      uses: canastro/copy-file-action@master
      with:
        source: "API/Cpp/shared/thermo.H"
        target: "GUI/include/shared/thermo.H"
    - name: Copy transport.H
      uses: canastro/copy-file-action@master
      with:
        source: "API/Cpp/shared/transport.H"
        target: "GUI/include/shared/transport.H"
    - name: Copy omega22.H
      uses: canastro/copy-file-action@master
      with:
        source: "API/Cpp/shared/omega22.H"
        target: "GUI/include/shared/omega22.H"
    - name: Copy omega11.H
      uses: canastro/copy-file-action@master
      with:
        source: "API/Cpp/shared/omega11.H"
        target: "GUI/include/shared/omega11.H"
